name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd electron_react
          npm install
      - name: Build
        run: |
          cd electron_react
          npm run build
      - name: Electron Build
        run: |
          cd electron_react
          npm run electron-build
      - name: List exe files
        run: |
          find electron_react/dist-electron -name "*.exe" -type f
        shell: bash
      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --notes "Automated release from electron_react"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload exe to Release
        run: |
          find electron_react/dist-electron -name "*.exe" -exec gh release upload ${{ github.ref_name }} {} \;
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
